error: add CertAlreadyReplaced variant (HTTP 409, alreadyReplaced URN)
Adds AcmeError::CertAlreadyReplaced returned when a client attempts to
create an order that replaces a certificate that has already been
superseded (RFC 9773 §5).  Maps to HTTP 409 Conflict and the
urn:ietf:params:acme:error:alreadyReplaced problem type.

Signed-off-by: Alexander Bokovoy <ab@samba.org>
Signed-off-by: Alexander Bokovoy <abokovoy@redhat.com>